export const SHOP = {
  name: "Minh Ngọc Quán",
  address: "Ấp Phú An Hòa, Xã Giao Long, tỉnh Vĩnh Long",
  phone: "0367 369 531",
};

export const CATEGORIES = ["Tất cả", "Lẩu", "Mì", "Ăn vặt", "Trà sữa", "Nước giải khát", "Nước có cồn"];


export const MENU = [
  { id: 1, name: "Cá Diêu Hồng (Nhỏ)", cat: "Lẩu", price: 89000, unit: "nồi" },
  { id: 2, name: "Cá Diêu Hồng (Lớn)", cat: "Lẩu", price: 159000, unit: "nồi" },
  { id: 3, name: "Cá Hú (Nhỏ)", cat: "Lẩu", price: 89000, unit: "nồi"},
  { id: 4, name: "Cá Hú (Lớn)", cat: "Lẩu", price: 159000, unit: "nồi" },
  { id: 5, name: "Đầu Cá Hồi (Nhỏ)", cat: "Lẩu", price: 89000, unit: "nồi"},
  { id: 6, name: "Đầu Cá Hồi (Lớn)", cat: "Lẩu", price: 159000, unit: "nồi" },
  { id: 7, name: "Thập Cẩm (Nhỏ)", cat: "Lẩu", price: 89000, unit: "nồi"},
  { id: 8, name: "Thập Cẩm (Lớn)", cat: "Lẩu", price: 159000, unit: "nồi" },
  { id: 9, name: "Thác Lác (Nhỏ)", cat: "Lẩu", price: 99000, unit: "nồi"},
  { id: 10, name: "Thác Lác (Lớn)", cat: "Lẩu", price: 169000, unit: "nồi" },
  { id: 11, name: "Hải Sản (Nhỏ)", cat: "Lẩu", price: 99000, unit: "nồi"},
  { id: 12, name: "Hải Sản (Lớn)", cat: "Lẩu", price: 169000, unit: "nồi" },
  { id: 13, name: "Xào Thập Cẩm", cat: "Mì", price: 75000, unit: "dĩa"},
  { id: 14, name: "Xào Hải Sản", cat: "Mì", price: 75000, unit: "dĩa"},
  { id: 15, name: "Xào Bò", cat: "Mì", price: 65000, unit: "dĩa"},
  { id: 16, name: "Cá Viên Chiên Thập Cẩm (Nhỏ)", cat: "Ăn vặt", price: 35000, unit: "phần"},
  { id: 17, name: "Cá Viên Chiên Thập Cẩm (Lớn)", cat: "Ăn vặt", price: 70000, unit: "phần"},
  { id: 18, name: "Cá Viên Chiên Sốt Me (Nhỏ)", cat: "Ăn vặt", price: 35000, unit: "phần"},
  { id: 19, name: "Cá Viên Chiên Sốt Me (Lớn)", cat: "Ăn vặt", price: 70000, unit: "phần"},
  { id: 20, name: "Cá Viên Chiên Nước Mắm (Nhỏ)", cat: "Ăn vặt", price: 35000, unit: "phần"},
  { id: 21, name: "Cá Viên Chiên Nước Mắm (Lớn)", cat: "Ăn vặt", price: 70000, unit: "phần"},
  { id: 22, name: "Khoai Tây Chiên (Nhỏ)", cat: "Ăn vặt", price: 20000, unit: "phần"},
  { id: 23, name: "Khoai Tây Chiên (Lớn)", cat: "Ăn vặt", price: 40000, unit: "phần"},
  { id: 24, name: "Khoai Tây Chiên Lắc Phô Mai (Nhỏ)", cat: "Ăn vặt", price: 20000, unit: "phần"},
  { id: 25, name: "Khoai Tây Chiên Lắc Phô Mai (Lớn)", cat: "Ăn vặt", price: 40000, unit: "phần"},
  { id: 26, name: "Xúc Xích Nhân Sốt Phô Mai", cat: "Ăn vặt", price: 10000, unit: "cây"},
  { id: 27, name: "Xúc Xích Lốc Xoáy", cat: "Ăn vặt", price: 10000, unit: "cây"},
  { id: 28, name: "Xúc Xích Đức", cat: "Ăn vặt", price: 10000, unit: "cây"},
  { id: 29, name: "Phô Mai Que", cat: "Ăn vặt", price: 10000, unit: "cây"},
  { id: 30, name: "Hotdog Ức Gà", cat: "Ăn vặt", price: 7000, unit: "cây"},
  { id: 31, name: "Truyền Thống", cat: "Trà sữa", price: 20000, unit: "ly"},
  { id: 32, name: "Socola", cat: "Trà sữa", price: 20000, unit: "ly"},
  { id: 33, name: "Thái Xanh", cat: "Trà sữa", price: 20000, unit: "ly"},
  { id: 34, name: "Thái Đỏ", cat: "Trà sữa", price: 20000, unit: "ly"},
  { id: 35, name: "Matcha", cat: "Trà sữa", price: 20000, unit: "ly"},
  { id: 36, name: "Cozy Đào", cat: "Nước giải khát", price: 12000, unit: "lon"},
  { id: 37, name: "Cozy Ổi", cat: "Nước giải khát", price: 12000, unit: "lon"},
  { id: 38, name: "Cozy Xoài", cat: "Nước giải khát", price: 12000, unit: "lon"},
  { id: 39, name: "Cozy Tắc Mật Ong", cat: "Nước giải khát", price: 12000, unit: "lon"},
  { id: 40, name: "Cozy Bí Đao", cat: "Nước giải khát", price: 12000, unit: "lon"},
  { id: 41, name: "Trà Xanh 0 Độ", cat: "Nước giải khát", price: 12000, unit: "chai"},
  { id: 42, name: "C2", cat: "Nước giải khát", price: 12000, unit: "chai"},
  { id: 43, name: "Ô Long", cat: "Nước giải khát", price: 12000, unit: "chai"},
  { id: 44, name: "Sting Đỏ/Vàng", cat: "Nước giải khát", price: 12000, unit: "chai"},
  { id: 45, name: "Coca Cola", cat: "Nước giải khát", price: 12000, unit: "lon"},
  { id: 46, name: "Pepsi", cat: "Nước giải khát", price: 12000, unit: "lon"},
  { id: 47, name: "Bò Húc", cat: "Nước giải khát", price: 15000, unit: "lon"},
  { id: 48, name: "Nước Suối", cat: "Nước giải khát", price: 7000, unit: "chai"},
  { id: 49, name: "Tiger Bạc", cat: "Nước có cồn", price: 20000, unit: "lon"},
  { id: 50, name: "Lague", cat: "Nước có cồn", price: 17000, unit: "lon"},
  { id: 51, name: "Sài Gòn Xanh", cat: "Nước có cồn", price: 15000, unit: "lon"},
  { id: 52, name: "Rượu Chuối Hột", cat: "Nước có cồn", price: 90000, unit: "chai"},

];